##########################################################
# SERVER
##########################################################
server:
  port: 40000

##########################################################
# DATASOURCE
##########################################################
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blue_builder
    username: blue_builder
    password: 1234
  jpa:
    hibernate:
      dialet: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update      # ddl 없으면 create, 있으면 update
    properties:
      hibernate:
        format_sql: true
    show-sql: true


  ##########################################################
  # REDIS
  ##########################################################
  spring:
    cache.type: redis
    redis:
      host: localhost
      port: 6379

##########################################################
# JWT
##########################################################
jwt.secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345